# Generated by Django 2.2.2 on 2019-06-24 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [    
        ('shelf', '0001_initial'),
    ]

    operations = [
    ]
