# Generated by Django 2.2.2 on 2019-06-24 21:04

from django.db import migrations
from django.db import migrations
from django.conf import settings
import os
import csv

def data_pull(apps, schema_editor):
    Category = apps.get_model('shelf', 'Category')
    Book = apps.get_model('shelf', 'Book')

    category = Category(name="")
    category.save()

    filename = os.path.join(settings.BASE_DIR, 'sample_books.csv')

    with open(filename) as file:
        reader = csv.DictReader(file)



        for row in reader:
            book = Book(title=row['title'], author=row['author'], url_address=row['url'], description=row['description'])
            book.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_auto_20190624_1654'),
    ]

    operations = [
        migrations.RunPython(data_pull),
    ]
