# Generated by Django 2.2.2 on 2019-06-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0004_auto_20190624_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
