# Generated by Django 2.2.2 on 2019-06-28 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0006_favorite_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
